spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tjackiz/environment-variables.git
          clone-on-start: true
          default-label: develop

server:
  port: ${port:8888}
